### ISSUE TITLE
Cannot create /backup/ directory because of permission denied error in network_backup.yml

### ISSUE THREAD

**Issue by hiyokotaisa** [network-automation/toolkit#22]
The task `Create a directory if it does not exist` has been failed because of there is no `become: yes` option.

```
TASK [Create a directory if it does not exist] *
fatal: [rtr2 -> backup-server(54.169.134.223)]: FAILED! => {"changed": false, "msg": "There was an issue creating /backup as requested: [Errno 13] Permission denied: b'/backup'", "path": "/backup/"}
```

When I add become into the [playbook](https://github.com/network-automation/toolkit/blob/master/playbooks/network_backup.yml), It worked without issue:

```yaml
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backup/
        state: directory
      delegate_to: backup-server
      run_once: true
      become: yes
```
